SELECT COUNT(*) AS total_students
FROM STDUENT;

SELECT COUNT(*) AS TOTAL_FACULTY 
FROM STDUENT;

SELECT COUNT(*) AS TOTAL_COURSE
FROM COURSE;

SELECT MAX(C.COURSE_CREDITS) AS MAX_CREADIT
FROM COURSE C;

SELECT MIN(C.COURSE_CREDITS) AS MIN_CREADIT
FROM COURSE C;

SELECT S.DEPT_ID ,COUNT(S.STD_ID)AS TOTAL_STUDENTS
FROM STDUENT S
GROUP BY S.DEPT_ID;

SELECT * FROM STDUENT;


SELECT F.DEPT_ID ,COUNT(F.FAC_ID)AS TOTAL_FACULTY
FROM FACULTY F
GROUP BY F.DEPT_ID;


SELECT C.DEPT_ID ,COUNT(C.FAC_ID)AS TOTAL_COURSE
FROM COURSE C
GROUP BY C.DEPT_ID;



SELECT E.SEMESTER ,COUNT(E.ENROLLMENT_ID)AS TOTAL_ENROLLMENT
FROM ENROLLMENT E
GROUP BY E.SEMESTER;

SELECT E.GRADE ,COUNT(E.ENROLLMENT_ID)AS TOTAL_ENROLLMENT
FROM ENROLLMENT E
GROUP BY E.GRADE;



SELECT S.DEPT_ID ,COUNT(S.STD_ID)AS TOTAL_STUDENT
FROM STDUENT S
GROUP BY S.DEPT_ID
HAVING TOTAL_STUDENT > 3 ;

SELECT E.SEMESTER ,COUNT(E.STD_ID)AS TOTAL_STUDENT
FROM ENROLLMENT E
GROUP BY E.SEMESTER
HAVING TOTAL_STUDENT > 3 ;



SELECT E.GRADE ,COUNT(E.STD_ID)AS TOTAL_STUDENT
FROM ENROLLMENT E
GROUP BY E.GRADE
HAVING TOTAL_STUDENT > 1 ;



SELECT C.DEPT_ID ,COUNT(C.COURSE_ID)AS TOTAL_COURSE
FROM COURSE C
GROUP BY C.DEPT_ID
HAVING TOTAL_COURSE > 1 ;



SELECT C.COURSE_ID ,COUNT(C.ENROLLMENT_ID)AS TOTAL_ENROLL
FROM ENROLLMENT C 
GROUP BY C.COURSE_ID;


SELECT E.COURSE_NAME,COUNT(C.ENROLLMENT_ID)AS TOTAL_ENROLL 
FROM ENROLLMENT C 
INNER JOIN COURSE E
ON E.COURSE_ID=C.COURSE_ID
GROUP BY C.COURSE_ID,E.COURSE_NAME;


SELECT F.FAC_NAME ,COUNT(C.COURSE_ID) AS TOTAL_COURSE
FROM COURSE C 
INNER JOIN FACULTY F
ON F.FAC_ID = C.FAC_ID
GROUP BY F.FAC_NAME;


SELECT C.COURSE_NAME ,MAX(E.GRADE) AS MAX_GRADE
FROM ENROLLMENT E
INNER JOIN COURSE C
ON C.COURSE_ID=E.COURSE_ID
GROUP BY C.COURSE_NAME;


SELECT C.DEPT_ID , COUNT(C.COURSE_ID) AS TOTAL_COURSE
FROM COURSE C
GROUP BY C.DEPT_ID;



SELECT E.SEMESTER , COUNT(E.ENROLLMENT_ID) AS TOTAL_STUDENT
FROM ENROLLMENT E
GROUP BY E.SEMESTER;



SELECT E.COURSE_ID , COUNT(E.ENROLLMENT_ID) AS TOTAL_STUDENT
FROM ENROLLMENT E
GROUP BY E.COURSE_ID
HAVING TOTAL_STUDENT >2;
