SELECT S.STD_NAME ,S.STD_ID,E.COURSE_ID 
FROM STDUENT  S 
INNER JOIN ENROLLMENT  E
ON S.STD_ID= E.STD_ID;



SELECT S.STD_NAME ,E.GRADE 
FROM STDUENT S 
INNER JOIN ENROLLMENT E
ON S.STD_ID= E.STD_ID;



SELECT S.STD_NAME ,E.GRADE ,E.COURSE_ID ,C.COURSE_NAME
FROM STDUENT S 
INNER JOIN ENROLLMENT E
ON S.STD_ID= E.STD_ID
INNER JOIN COURSE C 
ON E.COURSE_ID=C.COURSE_ID;



SELECT C.COURSE_NAME,C.COURSE_CREDITS,F.FAC_NAME
FROM COURSE C 
INNER JOIN FACULTY F 
ON C.DEPT_ID=F.DEPT_ID;



SELECT C.COURSE_NAME,F.FAC_NAME 
FROM COURSE C 
INNER JOIN FACULTY F
ON C.DEPT_ID=F.DEPT_ID
WHERE F.FAC_ID = 111;



SELECT F.FAC_NAME , F.FAC_EMAIL,C.COURSE_NAME
FROM FACULTY F
INNER JOIN COURSE C
ON F.DEPT_ID=C.DEPT_ID


SELECT S.STD_NAME ,C.COURSE_NAME
FROM STDUENT S
INNER JOIN ENROLLMENT E 
ON S.STD_ID=E.STD_ID
INNER JOIN COURSE C
ON C.COURSE_ID=E.COURSE_ID;


SELECT S.STD_NAME ,C.COURSE_NAME ,E.SEMESTER
FROM STDUENT S
INNER JOIN ENROLLMENT E 
ON S.STD_ID=E.STD_ID
INNER JOIN COURSE C
ON C.COURSE_ID=E.COURSE_ID;


SELECT S.STD_NAME ,C.COURSE_NAME ,E.SEMESTER
FROM STDUENT S
INNER JOIN ENROLLMENT E 
ON S.STD_ID=E.STD_ID
INNER JOIN COURSE C
ON C.COURSE_ID=E.COURSE_ID
WHERE E.SEMESTER = 'sem3'
;




SELECT S.STD_NAME ,C.COURSE_NAME ,E.SEMESTER
FROM STDUENT S
INNER JOIN ENROLLMENT E 
ON S.STD_ID=E.STD_ID
INNER JOIN COURSE C
ON C.COURSE_ID=E.COURSE_ID
WHERE S.STD_ID = 23729

;



SELECT s.STD_NAME , s.DEPT_ID, c.COURSE_NAME
FROM STDUENT s 
INNER JOIN COURSE c
ON c.DEPT_ID = s.DEPT_ID;


SELECT D.DEPT_ID , C.COURSE_NAME
FROM DEPARTMENT D
INNER JOIN COURSE C
ON C.DEPT_ID=D.DEPT_ID;



SELECT F.FAC_NAME , D.DEPT_NAME
FROM FACULTY F
INNER JOIN DEPARTMENT D
ON D.DEPT_ID = F.DEPT_ID;





SELECT S.STD_NAME ,C.COURSE_NAME ,S.DEPT_ID
FROM STDUENT S
INNER JOIN COURSE C
ON S.DEPT_ID = C.DEPT_ID
WHERE S.DEPT_ID = 5;



SELECT S.STD_NAME , C.COURSE_NAME
FROM STDUENT S 
INNER JOIN COURSE C
ON S.DEPT_ID=C.DEPT_ID
ORDER BY S.STD_NAME;


SELECT F.FAC_NAME , C.COURSE_NAME , C.COURSE_CREDITS
FROM FACULTY F 
INNER JOIN COURSE C
ON F.DEPT_ID=C.DEPT_ID
ORDER BY C.COURSE_CREDITS;



SELECT C.COURSE_NAME ,COUNT(E.STD_ID) AS TOTAL_STUDENT
FROM COURSE C 
INNER JOIN ENROLLMENT E 
ON E.COURSE_ID=C.COURSE_ID
GROUP BY C.C.COURSE_NAME;


SELECT F.FAC_NAME ,COUNT(C.COURSE_ID) AS TOTAL_TECH_SUB
FROM COURSE C 
INNER JOIN FACULTY F 
ON F.DEPT_ID=C.DEPT_ID
GROUP BY F.FAC_NAME;


SELECT S.DEPT_ID ,COUNT(S.STD_ID) AS TOTAL_STD 
FROM STDUENT S 
GROUP BY S.DEPT_ID;



SELECT C.COURSE_NAME,MAX(E.GRADE) AS MAX_GRADE
FROM COURSE C 
INNER JOIN ENROLLMENT E
ON C.COURSE_ID = E.COURSE_ID
GROUP BY C.COURSE_NAME;
